// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/health.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var health_default = defineTool({
  name: "health_check",
  title: "Health check",
  description: "Verify connectivity to the G\xE1s F\xE1cil MCP server and echo an optional message.",
  inputSchema: {
    message: z.string().optional().describe("Optional message to echo back.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ message }) => ({
    content: [
      {
        type: "text",
        text: `G\xE1s F\xE1cil MCP server OK. ${message ? `Echo: ${message}` : "No message provided."} Time: ${(/* @__PURE__ */ new Date()).toISOString()}`
      }
    ]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "gasfacil-mcp",
  title: "G\xE1s F\xE1cil MCP",
  version: "0.1.0",
  instructions: "MCP server for the G\xE1s F\xE1cil ERP. Use `health_check` to verify connectivity. Additional tools can be added under src/lib/mcp/tools/.",
  tools: [health_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
